aviatrix_controller_ip              = "54.151.96.222"
aviatrix_username                   = "admin"
aviatrix_password                   = "Aviatrix123#"
gcp_account_name                    = "Salesforce-GCP"
gcloud_project_id                   = "rlee-01"
gcloud_project_credentials_filepath = "/Users/ronaldlee/Desktop/gcp-rlee-01.json"
# copilot_address                     = "54.241.109.249"